framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                    delay: 60000
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            App\Message\MailRegistration: async
            App\Message\MailValidationInscription: async
            App\Message\MailRemoveInscription: async
            App\Message\MailUpdateUserByAdmin: async
            App\Message\MailAddNewGame: async
            App\Message\MailEditGame: async
            App\Message\MailDeleteGame: async
            App\Message\MailNewGameComment: async
            App\Message\MailAddGameMasterToGame: async
            App\Message\MailDeleteGameMasterToGame: async
            App\Message\MailAddUserToGame: async
            App\Message\MailDeleteUserToGame: async
            App\Message\MailRefreshStatusGame: async
