version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5450"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
