# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.locales: [fr, en]
    user_picture_profil: '%kernel.project_dir%/public/pictures/users'
    game_picture: '%kernel.project_dir%/public/pictures/games'
    qr_codes: '%kernel.project_dir%/public/pictures/qr_codes'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FileUploader:
        arguments:
            $gamePictureDirectory: '%game_picture%'
            $userPictureDirectory: '%user_picture_profil%'
            $qrCodeDirectory: '%qr_codes%'
    App\Service\UserDeletionService:
        arguments:
            $gamePictureDirectory: '%game_picture%'
            $userPictureDirectory: '%user_picture_profil%'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
